# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4cf36de65adf346cdaf088f274c8eb2448e2da4d72df1d689c4a054c7d01effd501437536e58b291c5d023eb78a51e4b17344a1194b52d4d5c404822f941388

test:
  secret_key_base: 7ab519d1e0679ef05a8a7bf742f598965f6d758680289f22d3d87610466d0f19b59b825749331bdacec824742d2f628b44a8137e8517e66333023d328b338ff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
